# Nome da aplicação
quarkus.application.name=kidsgrace-analytics-service

# ========================================
# Configuração do canal de entrada "users"
# ========================================

# Canal user-analytics
mp.messaging.incoming.user-analytics.connector=smallrye-kafka

# Tópico Kafka
mp.messaging.incoming.user-analytics.topic=users.events

# Broker Kafka
mp.messaging.incoming.user-analytics.bootstrap.servers=localhost:9092

# Consumer Group
mp.messaging.incoming.user-analytics.group.id=kidsgrace-analytics-service


# ========================================
# Configuração do canal de entrada "toys"
# ========================================

# Canal toy-analytics
mp.messaging.incoming.toy-analytics.connector=smallrye-kafka

# Tópico Kafka
mp.messaging.incoming.toy-analytics.topic=toys.events

# Broker Kafka
mp.messaging.incoming.toy-analytics.bootstrap.servers=localhost:9092

# Consumer Group
mp.messaging.incoming.toy-analytics.group.id=kidsgrace-analytics-service

quarkus.swagger-ui.always-include=true


# ========================================
# MySQL
# ========================================

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/kidsgrace_analytics
quarkus.datasource.username=root
quarkus.datasource.password=root

# ========================================
# Hibernate ORM
# ========================================

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true


# Porta da aplicação
quarkus.http.port=8091